### ISSUE TITLE
Meta: Accessiblity Enhancements (ARIA)

### ISSUE THREAD

**Issue by nschonni** [jzaefferer/jquery-validation#706]
Accessiblity enhancements
- [x] Add `aria-required` for required elements #230 
- [ ] Using aria-invalid="true" for form elements that have an error.
- [ ] aria-live attribute for error message section https://github.com/jzaefferer/jquery-validation/issues/706#issuecomment-15375400

These might be masked under an `accessible`/`aria` option (I know you don't like adding more to the API) or as an optional extend method.

/cc @pjackson28

**Comment by jzaefferer** [comment]
I'm sorry for the lack of activity on this issue. Instead of leaving it open any longer, I decided to close old issues without trying to address them, to longer give the false impression that it will get addressed eventually.

To the reporter (or anyone else interested in this issue): If you're affected by the same issue, consider opening a new issue, with a testpage that shows the issue. Even better, try to fix the issue yourself, and improve the project by sending a pull request. This may seem daunting at first, but you'll likely learn some useful skills that you can apply elsewhere as well. And you can help keep this project alive. [We've documented how to do these things, too](https://github.com/jzaefferer/jquery-validation/blob/master/CONTRIBUTING.md). A patch is worth a thousand issues!

**Comment by staabm** [comment]
@jzaefferer fyi: I just ticked the 2nd box regarding aria-invalid, because this was added as a part of #796

**Comment by jzaefferer** [comment]
Nice, thanks.

**Comment by Nettsentrisk** [comment]
According to the latest recommendations, aria-required and aria-invalid should not be used on elements which already have the required attribute or which are invalid according to constraints: http://www.w3.org/TR/html-aria/#docconformance

For aria-invalid it says: "Only use the aria-invalid attribute for elements that are not allowed to have a readonly attribute in HTML5".

An aria-live should only be used on an error summary, not for individual error messages that are already associated via aria-describedby.
