### ISSUE TITLE
Use new github release page

### ISSUE THREAD

**Issue by nschonni** [jzaefferer/jquery-validation#870]
I moved the existing notes related to the tagged releases to https://github.com/jzaefferer/jquery-validation/releases
- [x] Tag old releases (1.6 and 1.7 appear to be in the history)
- [x] Attach zips to releases
- [ ] Delete old changelog.txt file

**Comment by jzaefferer** [comment]
I've going to keep the txt file for now.
